# Generated by Django 3.0.6 on 2020-05-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200513_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='if_feautred',
            new_name='is_feautred',
        ),
    ]
