# Generated by Django 3.0.6 on 2020-05-13 13:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200513_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_ar',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='overview_ar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=60),
        ),
    ]
