# Generated by Django 3.0.5 on 2020-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200516_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
    ]
