# Generated by Django 3.0.5 on 2020-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200517_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='article',
            name='overview_ar',
            field=models.TextField(max_length=120),
        ),
    ]
