# Generated by Django 3.0.5 on 2020-05-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='discription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='posts.Article'),
        ),
    ]
